[package]
name = "rcgen"
version = "0.8.9"
authors = ["est31 <MTest31@outlook.com>"]
description = "Rust X.509 certificate generator"
repository = "https://github.com/est31/rcgen"
documentation = "https://docs.rs/rcgen"
license = "MIT OR Apache-2.0"
readme = "README.md"

[lib]
name = "rcgen"
path = "src/lib.rs"

[[bin]]
name = "rcgen"
path = "src/main.rs"

[dependencies]
byteorder = { version = "1.0", optional = true }

[package.metadata.docs.rs]
features = ["byteorder"]

