name: ci

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [macOS-latest]
        toolchain: [nightly-2021-03-14]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Run the tests
      env:
        RUSTFLAGS: -D warnings
      run: |
         cargo test --all
    - name: Run the tests with byteorder enabled
      env:
        RUSTFLAGS: -D warnings
      run: |
         cargo test
